#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>

// Comment or uncomment to show or hide log messages
#define LOG_APP_MAIN 
// #define LOG_SNIFFER_INIT 
// #define LOG_SNIFFER 
#define LOG_WIFI_SCAN 
// #define LOG_MQTT

#define CORE_0 0
#define APP_MAIN_TAG "app_main"
#define INIT_SNIFFER_TAG "init_sniffer"
#define SNIFFER_TAG "sniffer"
#define WIFI_SCAN_TAG "wifi_scan"
#define MQTT_TAG "mqtt"
#define MIN_WIFI_CHANNEL 1
#define MAX_WIFI_CHANNEL 11
#define MAX_NUM_MAC_ADDR 100
#define MAC_ADDR_SIZE 6


#include "esp_system.h"
#include "esp_wifi.h"


#define EXAMPLE_ESP_WIFI_SSID "Cant afford ur own WiFi"
#define EXAMPLE_ESP_WIFI_PASS "Noyouc@nthaveit888"
#define EXAMPLE_ESP_MAXIMUM_RETRY 10

#if CONFIG_ESP_WPA3_SAE_PWE_HUNT_AND_PECK
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_HUNT_AND_PECK
#define EXAMPLE_H2E_IDENTIFIER ""
#elif CONFIG_ESP_WPA3_SAE_PWE_HASH_TO_ELEMENT
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_HASH_TO_ELEMENT
#define EXAMPLE_H2E_IDENTIFIER CONFIG_ESP_WIFI_PW_ID
#elif CONFIG_ESP_WPA3_SAE_PWE_BOTH
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_BOTH
#define EXAMPLE_H2E_IDENTIFIER CONFIG_ESP_WIFI_PW_ID
#endif
#if CONFIG_ESP_WIFI_AUTH_OPEN
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_OPEN
#elif CONFIG_ESP_WIFI_AUTH_WEP
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WEP
#elif CONFIG_ESP_WIFI_AUTH_WPA_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA_WPA2_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA3_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_WPA3_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WAPI_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif

#endif